apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  labels:
    auth.openshift.io/managed-certificate-type: ca-bundle
  name: ovn-ca
  namespace: hypershift-ovn
