---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovnkube-config
  namespace: hypershift-ovn
data:
  ovnkube.conf: |-
    [default]
    mtu="1400"
    cluster-subnets="10.128.0.0/14/23"
    encap-port="6081"
    enable-lflow-cache=true
    lflow-cache-limit-kb=1048576

    [kubernetes]
    service-cidrs="172.30.0.0/16"
    ovn-config-namespace="hypershift-ovn"
    apiserver="https://api-int.sriov.dev.metalkube.org:6443"
    host-network-namespace="openshift-host-network"
    platform-type="BareMetal"

    [ovnkubernetesfeature]
    enable-egress-ip=true
    enable-egress-firewall=true

    [gateway]
    mode=shared
    nodeport=true
