apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host
  namespace: hypershift-ovn
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ovn
  hostPath:
    path: /var/home/core/ovn
