---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-host
  namespace: hypershift-ovn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: ovn
