---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpod
spec:
  replicas: 10
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: quay.io/zshi/centos:httpd-iperf
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 300000; done;" ]
        imagePullPolicy: IfNotPresent
