---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovnkube-config
  namespace: clusters-ovn-hypershift
data:
  ovnkube.conf: |-
    [default]
    mtu="8901"
    cluster-subnets="10.132.0.0/14/23"
    encap-port="6081"
    enable-lflow-cache=true
    lflow-cache-limit-kb=1048576

    [kubernetes]
    service-cidrs="172.31.0.0/16"
    ovn-config-namespace="clusters-ovn-hypershift"
    # kubeconfig="/etc/kube/config/kubeconfig"
    # apiserver="https://ace4d72b2a6db48ca9ec578d6e73d015-24433636fc7f725c.elb.us-east-1.amazonaws.com:6443"
    apiserver="https://af50b6c2fb1f34497ab2a402ec8a996a-631206c45ec2fb8f.elb.us-east-1.amazonaws.com:6443"
    # apiserver="https://api-int.zshi-2022-02-28-management.devcluster.openshift.com:6443"
    host-network-namespace="openshift-host-network"

    [ovnkubernetesfeature]
    enable-egress-ip=true
    enable-egress-firewall=true

    [gateway]
    mode=shared
    nodeport=true
